---
- hosts: 'master, workerlab'
  become: yes
  vars: 
   pack_kube: ['kubelet', 'kubeadm', 'kubectl']
  tasks:

  - name: Habilitar transparent masquerading
    firewalld:
         masquerade: yes
         state: enabled
         permanent: yes

  - name: Creando el archivo k8s.conf
    copy: 
       dest: "/etc/sysctl.d/k8s.conf"
       content: |
            net.bridge.bridge-nf-call-ip6tables = 1
            net.bridge.bridge-nf-call-iptables = 1  
           
  - name: Reiniciando sysctl
    sysctl:
       name:  net.ipv4.ip_forward
       value: '1'
       sysctl_set: yes
       state: present
       reload: yes
            
  - name: Desactivar la particion de swap
    command: swapoff -a
 

  - name: Comentando las lineas de particion swap 
    replace:
         path: /etc/fstab
         regexp: '(^/.*swap*)'
         replace: '# \1'
  
  - name: Agregando repositorio CRI-O
    shell: |
      VERSION=1.24
      OS=CentOS_8_Stream
      sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/devel:kubic:libcontainers:stable.repo
      sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo

  - name: Instalando CRI-O
    yum: 
      name: crio
      state: present 
    ignore_errors: yes

  - name: Habilitando modulos Kernel 
    modprobe: 
      name: br_netfilter
      state: present
    
  - name: Iniciando CRI-O
    systemd:
      name: crio
      state: started
      enabled: yes 
      
  - name: Configurando kubernetes repositorio
    yum_repository:
      name: Kubernetes
      description: Repositorio de Kubernetes
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
      enabled: yes
      gpgcheck: yes
      repo_gpgcheck: yes
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg      
      exclude: kubelet kubeadm kubectl

  - name: Instalando kubernetes
    dnf:
      name: "{{ pack_kube }}"
      state: present
      disable_excludes: Kubernetes
  
  - name: Habilitando y iniciando kubernetes
    systemd:
      name: kubelet
      state: started
      enabled: yes
      masked: no

      
              


    

